image: python:3.10

stages:
  - test

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - export DISPLAY=$(grep nameserver /etc/resolv.conf | awk '{print $2}'):0.0
    - python -m unittest discover
