image: python:3.10

stages:
  - test

test:
  stage: test
  script:
    - uname
    - pip install -r requirements.txt
    - export DISPLAY=:0
    - export DISPLAY=unix$DISPLAY
    - python -m unittest discover
