image: python:3.10

stages:
  - test

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - echo "backend: Agg" > ~/.config/matplotlib/matplotlibrc
    - python -m unittest discover
