image: python:3.10

stages:
  - test

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - apt update
    - apt install xvfb
    - Xvfb :1 -screen 0 1920x1080x24+32 -fbdir /var/tmp &
    - export DISPLAY=:1
    - python -m unittest discover
